"""Add option symbol and instrument token fields for Kite API verification

Revision ID: 12a590ac5c92
Revises: 4a535648df36
Create Date: 2025-12-01 07:39:21.822756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a590ac5c92'
down_revision = '4a535648df36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_chain_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ce_strike_symbol', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ce_instrument_token', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pe_strike_symbol', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pe_instrument_token', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_chain_data', schema=None) as batch_op:
        batch_op.drop_column('pe_instrument_token')
        batch_op.drop_column('pe_strike_symbol')
        batch_op.drop_column('ce_instrument_token')
        batch_op.drop_column('ce_strike_symbol')

    # ### end Alembic commands ###
