"""Add high low open close to nifty_prices

Revision ID: ab0c2f4db6bc
Revises: 12a590ac5c92
Create Date: 2025-12-03 09:35:59.826197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0c2f4db6bc'
down_revision = '12a590ac5c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nifty_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('open', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nifty_prices', schema=None) as batch_op:
        batch_op.drop_column('close')
        batch_op.drop_column('open')
        batch_op.drop_column('low')
        batch_op.drop_column('high')

    # ### end Alembic commands ###
